name: essumin_mix
description: essumin app.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  string_normalizer: ^0.2.0
  url_launcher: ^6.0.4

  avatar_glow: ^2.0.2
  confetti: ^0.7.0

  flutter_tts: ^3.7.0
  speech_to_text: ^6.3.0

  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0

  intl: ^0.17.0

  firebase_core: ^2.3.0
  cloud_firestore: ^4.8.3
  firebase_storage: ^11.2.5
  image_picker: ^1.0.1

  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/siglas/
    - assets/data/simbologias/
    - assets/data/adicionales/
    - assets/images/simbologias/grua/
    - assets/images/simbologias/rigger/
    - assets/images/simbologias/rigger/gifs/
    - assets/images/
    - .env
